#############################################
#### dev cf-mgmt pipeline configuration
#############################################
resources:
- name: dev-config-repo
  type: git
  source:
    uri: ((grab cf-mgmt.dev.git_repo_uri))
    branch: ((grab cf-mgmt.dev.git_repo_branch))
    # only watch for changes in config directory
    paths: ["ci", "((grab cf-mgmt.dev.config_dir))"]
- name: dev-time-trigger
  type: time
  source:
    interval: ((grab cf-mgmt.dev.time-trigger))

jobs:
- name: dev-cf-config
  plan:
  - get: dev-config-repo
    trigger: true
  - task: create-orgs
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-orgs

  - task: shared-domains
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: shared-domains

  - task: create-security-groups
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-security-groups

  - task: assign-default-security-groups
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: assign-default-security-groups

  - task: delete-orgs
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: delete-orgs

  - task: update-orgs-metadata
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-orgs-metadata

  - task: create-org-private-domains
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-org-private-domains

  - task: service-access
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: service-access

  - task: share-org-private-domains
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: share-org-private-domains

  - task: create-spaces
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: create-spaces

  - task: delete-spaces
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: delete-spaces

  - task: update-spaces
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-spaces

  - task: update-spaces-metadata
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-spaces-metadata

  - task: update-space-users
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LDAP_USER: ((grab cf-mgmt.dev.ldap_user))
      LDAP_PASSWORD: ((grab cf-mgmt.dev.ldap_password))
      LDAP_SERVER: ((grab cf-mgmt.dev.ldap_server))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-space-users

  - task: update-space-quotas
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-space-quotas

  - task: update-space-security-groups
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-space-security-groups

  - task: update-org-users
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LDAP_USER: ((grab cf-mgmt.dev.ldap_user))
      LDAP_PASSWORD: ((grab cf-mgmt.dev.ldap_password))
      LDAP_SERVER: ((grab cf-mgmt.dev.ldap_server))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-org-users

  - task: update-org-quotas
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: update-org-quotas

- name: dev-isolation-segments
  plan:
  - get: dev-config-repo
    trigger: true
    passed: [create-orgs, create-spaces]
  - get: dev-time-trigger
    trigger: true
  - task: isolation-segments
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: isolation-segments

- name: dev-cleanup-org-users
  plan:
  - get: dev-config-repo
    passed: [update-org-users,update-space-users]
    trigger: true
  - get: dev-time-trigger
    trigger: true
  - task: cleanup-org-users
    file: config-repo/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: ((grab cf-mgmt.dev.system_domain))
      USER_ID: ((grab cf-mgmt.dev.user_id))
      PASSWORD: ((grab cf-mgmt.dev.password))
      CONFIG_DIR: ((grab cf-mgmt.dev.config_dir))
      CLIENT_SECRET: ((grab cf-mgmt.dev.client_secret))
      LOG_LEVEL: ((grab cf-mgmt.dev.log_level))
      CF_MGMT_COMMAND: cleanup-org-users
