orgs:
- system
- services
- segment
- cats-and-dogs
- windows-org
- windows-2-org
enable-delete-orgs: false
protected_orgs:
- ^system$
- splunk-nozzle-org
- redis-test-ORG
- appdynamics-org
- credhub-service-broker-org
- ^p-
