enable-delete-isolation-segments: false
enable-unassign-security-groups: false
running-security-groups:
- public_networks
- dns
- private_networks
staging-security-groups:
- public_networks
- dns
- private_networks
shared-domains:
  apps.codex.starkandwayne.com:
    internal: false
  apps.internal:
    internal: true
  tcp2.apps.codex.starkandwayne.com:
    internal: false
    router-group: default-tcp
enable-remove-shared-domains: true
metadata-prefix: cf-mgmt.pivotal.io
enable-service-access: true
ignore-legacy-service-access: false
service-access:
- broker: smbbroker
  services:
  - service: smb
    all_access_plans:
    - Existing
- broker: dev-blacksmith
  services:
  - service: rabbitmq
    all_access_plans:
    - small-cluster
    - small-dedicated
- broker: nfsbroker
  services:
  - service: nfs-legacy
    no_access_plans:
    - Existing
  - service: nfs
    all_access_plans:
    - Existing
- broker: autoscaler
  services:
  - service: autoscaler
    all_access_plans:
    - autoscaler-free-plan
protected-users: []
